version: '3.4'

networks:
  mynetworkapi:

services:
  sqlserverdocker:
    container_name: sql-server-docker
    image: mcr.microsoft.com/mssql/server
    ports:
       - 8006:1433
    environment:
       - ACCEPT_EULA=Y
       - MSSQL_SA_PASSWORD=alizee010419!
    networks:
        - mynetworkapi

  webapi_net8_docker:
    image: webapi_net8_docker
    build:
      context: .
      dockerfile: WebAPI_NET8_Docker/Dockerfile
    networks:
        - mynetworkapi
    depends_on:
        - sqlserverdocker
    ports:
        - 5001:8081
