version: '3.4'

services:
  webapi_net8_docker:
    image: webapi_net8_docker:dev
    container_name: "WebAPI_NET8_Docker_1"
    build:
      args:
        BUILD_CONFIGURATION: Debug
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WebAPI_NET8_Docker"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=/.nuget/fallbackpackages
    volumes:
      - D:\Proyectos\ASP.NET\1_Mis Proyectos\09.API_SQLServer_Docker_Compose\WebAPI_NET8_Docker_Compose\microservicio-web-api-net8-docker-bd\WebAPI_NET8_Docker:/app:rw
      - D:\Proyectos\ASP.NET\1_Mis Proyectos\09.API_SQLServer_Docker_Compose\WebAPI_NET8_Docker_Compose\microservicio-web-api-net8-docker-bd:/src:rw
      - C:\Users\chels\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\chels\.nuget\packages:/.nuget/packages:ro
      - C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages:/.nuget/fallbackpackages:ro
      - C:\Users\chels\AppData\Roaming\ASP.NET\Https:/root/.aspnet/https:ro
      - C:\Users\chels\AppData\Roaming\ASP.NET\Https:/home/app/.aspnet/https:ro
      - C:\Users\chels\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets:ro
      - C:\Users\chels\AppData\Roaming\Microsoft\UserSecrets:/home/app/.microsoft/usersecrets:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Sdks\Microsoft.Docker.Sdk\tools\linux-x64\net8.0:/VSTools:ro
      - C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\HotReload:/HotReloadAgent:ro

    entrypoint: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --wait"
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /.nuget/packages --additionalProbingPath /.nuget/fallbackpackages  \"/app/bin/Debug/net8.0/WebAPI_NET8_Docker.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "dotnet --roll-forward Major /VSTools/DistrolessHelper/DistrolessHelper.dll --stop dotnet"
    tty: true